# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\"P\n\x0ctest_message\x12\x13\n\x0buser_number\x18\x01 \x01(\x05\x12\x14\n\x0cuser_message\x18\x02 \x01(\t\x12\x15\n\rextra_details\x18\x03 \x03(\tb\x06proto3')
)




_TEST_MESSAGE = _descriptor.Descriptor(
  name='test_message',
  full_name='test_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_number', full_name='test_message.user_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_message', full_name='test_message.user_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_details', full_name='test_message.extra_details', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['test_message'] = _TEST_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

test_message = _reflection.GeneratedProtocolMessageType('test_message', (_message.Message,), dict(
  DESCRIPTOR = _TEST_MESSAGE,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test_message)
  ))
_sym_db.RegisterMessage(test_message)


# @@protoc_insertion_point(module_scope)
